org.gradle.jvmargs=-Xmx1G

# Mod properties
platform.versions=1.21.11
mod.name=Camerapture
mod.version=1.10.11
mod.group=me.chrr

# Parchment properties
parchment.version=1.21.11:2025.12.20

# Fabric properties
# check these on https://modmuss50.me/fabric.html
fabric.loaderVersion=0.18.3
fabric.apiVersion=0.140.2+1.21.11

# NeoForge properties
# check these on https://projects.neoforged.net/neoforged/neoforge
neoforge.version=21.11.13-beta

# Dependency properties
# check these on https://linkie.shedaniel.dev/
modmenu.version=14.0.0-rc.2
clothconfig.version=18.0.145
firstpersonmodel.version=2.4.6
jade.version=17.0.1

# Distribution properties
modrinth.id=9dzLWnmZ
curseforge.id=1051342