org.gradle.jvmargs=-Xmx1G

# Mod properties
platform.versions=1.21.9,1.21.10
mod.name=Camerapture
mod.version=1.10.7
mod.group=me.chrr

# Fabric properties
# check these on https://modmuss50.me/fabric.html
fabric.yarnVersion=1.21.9+build.1
fabric.loaderVersion=0.17.2
fabric.apiVersion=0.134.0+1.21.9

# NeoForge properties
# check these on https://projects.neoforged.net/neoforged/neoforge
# check mappings patch version on https://maven.architectury.dev/dev/architectury/yarn-mappings-patch-neoforge/
neoforge.version=21.9.6-beta
neoforge.yarnPatch=1.21+build.4

# Dependency properties
# check these on https://linkie.shedaniel.dev/
modmenu.version=14.0.0-rc.2
clothconfig.version=18.0.145
firstpersonmodel.version=2.4.6
jade.version=17.0.1

# Distribution properties
modrinth.id=9dzLWnmZ
curseforge.id=1051342