org.gradle.jvmargs=-Xmx1G

minecraft.version=26.2
minecraft.compatible=~26.2

fabric.loader.version=0.19.3
fabric.api.version=0.152.1+26.2

neoforge.version=26.2.0.0-beta

modmenu.version=18.0.0-alpha.5
clothconfig.version=26.1.154
firstpersonmodel.version=2.4.6
jade.version=26.0.2
tapestry.version=1.1.2+mc26.2

mod.version=2.0.0