name: Bug Report
description: Found an issue? Submit a report!
labels: ["bug"]
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: What's the issue?
      description: What's the problem? Describe what happened, add screenshots and log files!
  - type: dropdown
    id: loader
    attributes:
      label: What loader are you using?
      multiple: true
      options:
        - Forge
        - NeoForge
        - Fabric
        - Quilt
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What is your Minecraft version?
      placeholder: ex. 1.20.1
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What is Camerapture's version?
      description: Don't know them? Please check either the filename of the mod, or look in your in-game mod menu.
      placeholder: ex. Camerapture 1.6.4