name: Build

on:
  push:
    branches: [ "1.*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build for all platforms
        run: ./gradlew buildAll

      - uses: actions/upload-artifact@v4
        with:
          name: 'mod-jars'
          path: 'build/libs/*.jar'